### ISSUE TITLE
Método demasiado largo

### ISSUE THREAD

**Issue by delucas** [Donald-Knuth/ProyectoAsistente#13]
Este método podría dividirse, con métodos privados... o utilizar un despacho dinámico polimórfico.

https://github.com/Donald-Knuth/ProyectoAsistente/blob/22ff2808cd299b8ed24787ccbf5a69ec7420809a/src/atencion/ManejoDeuda.java#L23

**Comment by OriaJoaquin** [comment]
Se refactorizó el método atender de la clase ManejoDeuda.
